<?php

/*
 * Hook form alter
 */
function ms_link_stats_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
	//check node edit form and then attach library
	  if (method_exists($form_state, 'getFormObject') && method_exists($form_state->getFormObject(), 'getOperation') && $form_state->getFormObject()->getOperation() == 'edit') {
	  	$href = \Drupal::request()->get('href');
		if ($href && isset($form['body'])) {
			// Add library
			$form['#attached']['library'][] = 'ms_link_stats/custom';
		}
	  }
}


/*
 * Hook entity type presave
 */
function ms_link_stats_node_presave(Drupal\node\NodeInterface $node) {
	//check node has body
	if ($node && $node->hasField('body')) {
		$body_data = $node->get('body')->getValue();
		if ($body_data) {
			//check each body and replace if bg color
			foreach ($body_data as $key => &$value) {
				if (isset($value['value']) && $value['value']) {
					$value['value'] = str_replace("background-color: rgb(255, 255, 0);", "", $value['value']);
				}
				if (isset($value['summary']) && $value['summary']) {
					$value['summary'] = str_replace("background-color: rgb(255, 255, 0);", "", $value['summary']);
				}

			}
		}
		//replace node body without bg color
		$node->body = $body_data;
	}

}